### ISSUE TITLE
Depends on gradle tasks only if project is affected

### ISSUE THREAD

**Issue by kozaxinan** [dropbox/AffectedModuleDetector#223]
The current setup depends on the task we configure and setup with `onlyIf` independent to dependsOn.

For example; `assembleAffectedAndroidTests` configures task's dependsOn and onlyIf. dependsOn assembleAffectedAndroidTests even when onlyIf is false.

That causes assembleAffectedAndroidTests become SKIPPED but gradle runs all depending tasks including assembleDebugAndroidTest because of they are set with dependsOn.

I managed to have expected result with a custom Task.

```
        project
            .tasks
            .register("buildAndroidTests") {
                val task = it.project.tasks.findByName("assembleDebugAndroidTest")
                if (task != null && AffectedModuleDetector.isProjectAffected(it.project)) {
                    it.dependsOn(task)
                }
            }

affectedModuleDetector {
  ....
  customTasks = setOf(
                    AffectedModuleConfiguration.CustomTask(
                        commandByImpact = "buildAffectedAndroidTests",
                        originalGradleCommand = "buildAndroidTests",
                        taskDescription = "This task builds all Android tests that are affected by the current changes."
                    )
                )
}
```

When I call `buildAffectedAndroidTests` it calls the `buildAndroidTests`. Only affected `buildAndroidTests` will dependsOn `assembleDebugAndroidTest`.

dependsOn only needs to be set when task's will run (same as onlyIf)

**Comment by joshafeinberg** [comment]
Hey, so I've taken some look at this and not sure how easy of a fix this will be. We might have to traverse the entire build tree which is turning out to be a bit more complicated so that we can manually remove those jobs. I also need to do some research into gradle to see if theres like an easy way to "find all parent tasks" but guessing that doesn't work well with how configuration goes.

Will keep investigating when I have time (sorry this has been so delayed, I've switched to the manager world so not much time for this) and hopefully come up with something clever

**Comment by ss0930** [comment]
@kozaxinan 

```
 project
            .tasks
            .register("buildAndroidTests") {
                val task = it.project.tasks.findByName("assembleDebugAndroidTest")
                if (task != null && AffectedModuleDetector.isProjectAffected(it.project)) {
                    it.dependsOn(task)
                }
            }
```

I am not sure how this is working for you.

https://github.com/dropbox/AffectedModuleDetector/blob/a2a77a984c09921895a1e30ef49e50ba422682a8/affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt#L243
`isProjectAffected` can only be called during execution phase, yet here, if i understand correctly, it is being called in configuration phase.

I actually tried this same approach using a "wrapper" task as the custom task for AMD config and add `dependsOn` the actual task (`lint` task in my case) to execute if project is affected. I had 2 different results -

1. Tried the above approach on a small, 3 module sample app and this worked exactly as I wanted. I was able to call `isProjectAffected` in the configuration phase same as you mentioned.

2. Tried the above approach on company project w/ 500+ modules and would get an exception during configuration for calling `isProjectAffected` like this. If I moved `isProjectAffected` check to execution phase in `doFirst` or `doLast`, it worked fine. But in order to add `dependsOn` dependency, this check needs to be done in the configuration phase.

I am not sure why it works in the smaller sample app project and not in the main project 🤔 

This is the error I get in the main project :
> Extension with name 'AffectedModuleDetectorPlugin' does not exist. Currently registered extension names: [ext, buildScan, gradleEnterprise, buildLibs, libs, versionCatalogs, projects, fladle, emerge, untangler, affectedModuleDetector, googleJavaFormat, sonar, sonarqube, reporting, detekt, dependencyAnalysis]

**Comment by cpaleop** [comment]
@ss0930 From the error I can tell that you are trying to configure this plugin even though is not (yet?) available, meaning that the plugin might not have yet - or even at all - been applied to your module.

Regarding the main point; it seems pretty close to impossible to achieve this. There is a case where multiple tasks are being executed from a single Gradle invocation. For example `./gradlew affectedLintDebug detektDebug`. Let's say that `affectedLintDebug` has marked a dependency task `common:compileDebugKotlin` as `SKIPPED`.

In that case there is no guarantee that `detektDebug` is not depending on `common:compileDebugKotlin`. If it does, then it would not be wise from AMD to mark it as `SKIPPED` since Detekt needs it.

The above is just a guess, I didn't really try to verify this.

Since we are discussing this topic, it would be nice to try and completely exclude the non-affected tasks from execution, similar to what the `-x` or `--exclude-task` Gradle option does. In the  [documentation](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:excluding_tasks_from_the_command_line) they state:
> You can see that the `test` task is not executed, even though it depends on the `dist` task. The `test` task’s dependencies, such as `compileTest`, **are not executed either**. Those dependencies of `test` that another task requires, such as `compile`, are still executed.
